name: not_at_home
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #TRANSITIONS
  page_transition: ^1.1.4

  #CONTACT
  contacts_service: ^0.3.0
  contact_picker: ^0.0.2

  #ICONS
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0

  #IMAGE
  provider: ^2.0.1
  image_picker: ^0.6.0+16 
  image: ^2.1.4

  #PERMISSIONS
  permission: ^0.1.2
  #Works but isn't properly requesting a contact
  #permission_handler: ^3.2.0 #don't upgrade beyond this
  #Doesn't work at all
  #simple_permissions: ^0.1.9

  #STICKY HEADERS
  flutter_sticky_header: ^0.4.0 
  #Contains a customScrollView so does not let me add banner
  #sticky_infinite_list: ^1.2.2 
  #Added weird bounce to sticky header with the SliverAppBar
  #sticky_headers: "^0.1.8"
  #Basically a List View (good alt)
  #sticky_header_list: ^1.0.6 
  
  #OTHER
  #scrolled way to slow (animateTo or jumpTo) worked better
  scroll_to_index: any 
  vibration: ^1.2.1
  #map_view: ^0.0.14
  #indexed_list_view: ^0.0.5 #would work great IF it didn't require an infinitely scrolling list
  diacritic: ^0.1.1

  # share 
  # https://pub.dev/packages/share
  # https://pub.dev/packages/esys_flutter_share
  # https://pub.dev/packages/flutter_share_me

  # other
  # https://pub.dev/packages/diacritic

  # sticky headers
  # https://pub.dev/packages/sticky_headers
  # https://pub.dev/packages/flutter_sticky_header
  # https://pub.dev/packages/sticky_header_list

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
